name: Build and deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
    inputs:
      AZURE_FUNCTIONAPP_NAME:
        description: 'Azure Functions Name'
        required: true

env:
  APP_PATH: './src/CS/Api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build ${{ env.APP_PATH }} --configuration Release
      
      - name: dotnet publish
        run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{env.APP_PATH}}/myapi
      
      - name: Upload artifact to deployment job
        uses: actions/upload-artifact@v3
        with:
          name: functionapp
          path: ${{env.APP_PATH}}/myapi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: functionapp
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Function App
        id: deploy-to-functionapp
        uses: azure/functions-action@v1
        with:
          app-name: ${{ github.event.inputs.AZURE_FUNCTIONAPP_NAME }}
          package: .
