name: Build and deploy ASP.Net Core Web App to Azure App Service

on:
  workflow_dispatch:
    inputs:
      AZURE_WEBAPP_NAME:
        description: 'WebApp Name'
        required: true

env:
  APP_PATH: './src/CS/Web'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
      
